### ISSUE TITLE
Add a 2-week free unlimited rentals for class referrals.

### ISSUE THREAD

**Issue by oliverdan2009** [bectechana/AustinWindsurfSchool.github.io#6]

**Comment by oliverdan2009** [comment]
You could add the blurb right here: 
![image](https://github.com/bectechana/AustinWindsurfSchool.github.io/assets/73079162/1731cf2a-b944-4d5f-b420-e376169f5c7f)

**Comment by bectechana** [comment]
I added under weekend lesson dates is that good?
<img width="1220" alt="image" src="https://github.com/bectechana/AustinWindsurfSchool.github.io/assets/122305223/5c3be2c9-ccd7-4645-9800-33add4fe46dc">
